approval_policy = "never"
sandbox_mode = "danger-full-access"
model_provider = "intelalloc"
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
network_access = "enabled"
disable_response_storage = true
windows_wsl_setup_acknowledged = true
model_verbosity = "high"
 
[model_providers.intelalloc]
name = "intelalloc"
base_url = "https://backend.intelalloc.com"
wire_api = "responses"
requires_openai_auth = true